apiVersion: apps/v1
kind: Deployment
metadata:
  name: allcloud
spec:
  selector:
    matchLabels:
      app: nginx-deploy
      tier: allcloud
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: nginx-deploy
        tier: allcloud
    spec:
      containers:
      - name: nginx-deploy
        image: nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 20003
