apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy
  labels:
    app: nginx-deploy
    tier: nginx-deploy
spec:
  type: "{{ .Values.serviceType }}"
  ports:
  - port: 20003
  selector:
    app: nginx-deploy
    tier: nginx-deploy
