apiVersion: apps/v1
kind: Deployment
metadata:
  name: allcloud
spec:
  selector:
    matchLabels:
      app: webmin
      tier: allcloud
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: webmin
        tier: allcloud
    spec:
      containers:
      - name: webmin
        image: johanp/webmin:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 10000
